language: julia

os:
  - linux

julia:
  - 0.6

notifications:
  email: false

git:
  depth: 99999999

cache:
  timeout: 1000
  directories:
    - downloads

env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - BINARYBUILDER_AUTOMATIC_APPLE=true
#  matrix:
#  - TARGET=x86_64-linux-gnu

sudo: required

#jobs:
#  include:
#  - stage: regenerate build.jl
#    script: julia --color=yes build_tarballs.jl --only-buildjl
#    if: tag IS present

before_script:
  - julia -e 'VERSION >= v"0.7-" && exit(); Pkg.clone("https://github.com/JuliaPackaging/BinaryBuilder.jl"); Pkg.build("BinaryBuilder");'
  - julia -e 'VERSION < v"0.7-" && exit(); using Pkg; Pkg.API.clone("https://github.com/JuliaPackaging/BinaryBuilder.jl"); Pkg.API.checkout("BinaryProvider", "master"); Pkg.API.build("BinaryBuilder");'

script:
  - julia --color=yes build_tarballs.jl

deploy:
  provider: releases
  api_key:
    # Note; this api_key is only valid for jgoldfar/SiloBuilder; you need
    # to make your own: https://docs.travis-ci.com/user/deployment/releases/
    secure: UFjvHFZup4HH7JHHhPWQHrHwIAtIxbUfDqpJGxKPbO+IaxcOFahlaYx7f/4j9+/6kbWIJnSfWQg1Etue93ac/+z4BZhrlPYwN4OEhJRJeeJrVXP3BKuC17xGfCE/wpS2DxzHaID/DkEc9Pl7Cpe3n0BEKSyHD0KP+ge9k1bgPEmgeHcQKuTbLbdKrK/gJFnhxMBvobXbnXFAQx5NWUDkJLr4vzTUylVRceY07YPJusZ7PeribmQZRhiExZANnJyLLXZ7OK6JOUAZ7eVOfXfEVCQhGEjEXN4yce7BNjsp/fkk3e2tvrzfZvBH9oyEKcS44q8e2GOG/xTYfmrUpeUY5tYwh5pyv240ZD29PwQgtYNJE+L/w37OWcufIGN1zffz7oXKBUdFUOIwIdTcrPCsbjo9yGeGzZmSYfLbZrRkzsn3kPx21zc0i+6AIqIxY/u/DpU0FBp3JiXthkrusZSuRGA5QssFOP2uwNmhoE2vj/2t0+PUo5IZuox3q0QamOFsF3FV0WRVVu6DUm34k3FvEqHuOX7hn++1RLZvqbM0jqpFQBrWxdwd4C8YvelnMBYV+xuqO4fUAlbIiHruK01UrIsWg8j4jdC0RHuUkVfW4kywGnzTskCJhH3n4BPGtQXmOgf9gjFol+TXRD8z0d1YGlwBgMgDaPnxxzpydIKHLY8=
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: jgoldfar/SiloBuilder
    tags: true
